### ISSUE TITLE
Do you have a python version?

### ISSUE THREAD

**Issue by masterchop** [zanazakaryaie/ARM-VO#2]
I would like to run this on python :)

**Comment by zanazakaryaie** [comment]
The python version requires wrapper. I'm busy for a while and can't write it. But I would appreciate if you do it yourself and share the code with us

**Comment by masterchop** [comment]
i am a noob :( so no idea where to start, i heard that you can with boost but i dont understand C++ so not sure is a good idea i jump there, what do you think? do you have a quick direction to point me?

**Comment by aleonnet** [comment]
> The python version requires wrapper. I'm busy for a while and can't write it. But I would appreciate if you do it yourself and share the code with us

Hi @zanazakaryaie Do you mean it's not possible to port the code to python only?

By the way great job!

**Comment by zanazakaryaie** [comment]
Hi @aleonnet
Thank you.
ARM-VO uses [Neon Intrinsics](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics) in keypoint detection and tracking. These intrinsics are only available for C and C++. So it's not possible to port the code to python directly.

**Comment by aleonnet** [comment]
I see. Thanks for the clarification.

**Comment by zanazakaryaie** [comment]
There is a Python version available [here](https://github.com/wuyuanmm/ARM_VO_pybind)
