### ISSUE TITLE
opencv version?

### ISSUE THREAD

**Issue by poaongithub** [zanazakaryaie/ARM-VO#4]
hi, first of all, great work! 
I'm trying to test this code, but I'm getting an error "segmentation fault" on "parallel_for_(Range(0, npoints),..."  in function calc_OpticalFlowPyrLK.

This is my configuration:
1. Raspbian Bionic.
2. OpenCV 3.4.6 (build with neon and tbb).

any advice appreciates, Thanks in advance.
@zanazakaryaie

**Comment by zanazakaryaie** [comment]
Hi @poaongithub 
Thanks for your interest

So you have built OpenCV on Ubuntu Mate 18.04. Could you please post the output of `getBuildInformation()` function in OpenCV?

**Comment by poaongithub** [comment]
@zanazakaryaie ,
solved it by rebuild opencv with neon and tbb, thanks again.
