### ISSUE TITLE
How to improve the odemotry accuracy？ I found this method is not robust，when I change the camera and image(1280*720). But I want to apply this method to the actual scene , please help me, thanks

### ISSUE THREAD

**Issue by wuyuanmm** [zanazakaryaie/ARM-VO#7]

**Comment by zanazakaryaie** [comment]
Make sure you provide true calibration data in params.yaml file. There are several methods to increase accuracy. We have mentioned them in the paper.

**Comment by wuyuanmm** [comment]
Thank you for your reply. I tested this algorithm on the emulator (Carla), so the camera parameters should be correct.I will read this paper further and try to improve the accuracy of the algorithm

**Comment by wuyuanmm** [comment]
this is [python version](https://github.com/wuyuanmm/ARM_VO_pybind),  I fixed some operational issues。

**Comment by zanazakaryaie** [comment]
Greate @wuyuanmm 
Thanks for making the Python wrapper. I will add this to the Readme so that more users can find it.
