### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by jingyibo123** [zanazakaryaie/ARM-VO#9]
Dear contributors,

Congratulations on your  work and many thanks for sharing it!
However I couldn't find any information about license in this repo, a repo without license has ambiguous terms and could lead to [law suits](https://github.com/github/choosealicense.com/issues/196#issuecomment-103801120).....

**Comment by zanazakaryaie** [comment]
Hi. Feel free to use ARM-VO under MIT license
